### ISSUE TITLE
Missing function clause in terminate callback (cowboy adapter)

### ISSUE THREAD

**Issue by focused** [phoenixframework/websock_adapter#19]
When I got an error the terminate callback can not handle it correctly:
```
"** (FunctionClauseError) no function clause matching in WebSockAdapter.CowboyAdapter.terminate/3\n    (websock_adapter 0.5.7) lib/websock_adapter/cowboy_adapter.ex:52: 

WebSockAdapter.CowboyAdapter.terminate({:crash, :error, :function_clause}, %{port: 443, scheme: \"https\", version: :\"HTTP/1.1\", path: \"*****\", host: \"*****\", peer: {{*, *, *, *}, *}, method: \"GET\", qs: \"\"}, {MyWSHandler, %{}, %MyWSHandler.State{...}})
...
```
Source:
https://github.com/phoenixframework/websock_adapter/blob/c4c6ea66a1d65436be869abc6224b90317e4950a/lib/websock_adapter/cowboy_adapter.ex#L71

It looks like the `terminate` callback awaits 2-elem tuple in the 3rd argument: `terminate(reason, _req, {handler, state})`, but there are 3 elements - ws handler module, some empty map (`%{}`) and the WS handler state.

Package versions:
```
cowboy "2.11.0"
plug "1.16.1"
plug_cowboy "2.6.2"
websock "0.5.3"
websock_adapter "0.5.7"
```
```
elixir 1.15.6-otp-26
erlang 26.1.1
```

**Comment by mtrudel** [comment]
Thanks for this - could you provide a more complete stacktrace so I can better figure out where tis is happening?

**Comment by focused** [comment]
```
[error] Ranch listener MyApp.Router.HTTP had connection process started with :cowboy_clear:start_link/4 at #PID<0.1203.0> exit with reason: {:function_clause, [{WebSockAdapter.CowboyAdapter, :terminate, [{:crash, :error, :function_clause}, %{port: 8080, scheme: "http", version: :"HTTP/1.1", path: "******", host: "127.0.0.1", peer: {{127, 0, 0, 1}, 57175}, method: "GET", qs: ""}, {MyApp.WSHandler, %{}, %MyApp.WSHandler.State{...}}], [file: ~c"lib/websock_adapter/cowboy_adapter.ex", line: 52]}, {:cowboy_websocket, :handler_call, 6, [file: ~c"/Users/d/Work/my-app/deps/cowboy/src/cowboy_websocket.erl", line: 564]}, {:cowboy_http, :loop, 1, [file: ~c"/Users/d/Work/my-app/deps/cowboy/src/cowboy_http.erl", line: 253]}, {:proc_lib, :init_p_do_apply, 3, [file: ~c"proc_lib.erl", line: 241]}]}
```

**Comment by mtrudel** [comment]
It looks like it's an issue with a crash *during* the upgrade process. It also looks like you may be returning tuple elements in the wrong order when you upgrade; I see `{MyApp.WSHandler, %{}, %MyApp.WSHandler.State{...}}` in the above stack trace, but the expected order is `{handler_mod, handler_state, cowboy_opts}`. Perhaps you have the last two elements reversed?

**Comment by focused** [comment]
It definitely happened after the upgrade in the `WebSock.init/1` callback.

There was a clause error in the part not related to the ws, and the standard clause elixir error is passed to the terminate callback, which in turn raises the clause error also.

**Comment by mtrudel** [comment]
Glad to hear you (sort of) got sorted. 

It would be *immensely* helpful to have a minimal repro for this, either as a [Garyfile](https://fly.io/phoenix-files/single-file-elixir-scripts/) or a repo

**Comment by focused** [comment]
Sure, I'll prepare it a couple of days.

**Comment by focused** [comment]
https://github.com/focused/websock_adapter_app/tree/main

Just run `mix test` (maybe increase delay `:timer.sleep(10)`) or call it in console:
```
iex(1)> {:ok, pid} = MyApp.WSClient.start_link()
```

**Comment by mtrudel** [comment]
Fix for this up at #20!

**Comment by mtrudel** [comment]
Related as part of 0.5.8!

**Comment by focused** [comment]
Thank you very much.
