### ISSUE TITLE
Dependency version requirements are too restrictive

### ISSUE THREAD

**Issue by moogle19** [phoenixframework/websock_adapter#5]
The version in the `mix.exs` are quite restrictive:

```elixir
{:websock, "~> 0.4.3"},
{:plug, "~> 1.14.0"},
{:bandit, "~> 0.5.9", optional: true},
```

Currently bandit 0.6.0 won't work without specifying `override: true`.

Can we switch it to go up to the next major version (e.g. `{:bandit, "~> 0.5"}`) for all three?

**Comment by mtrudel** [comment]
Done & published as 0.4.5
